# Generated by Django 4.2.3 on 2023-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='This page is main', max_length=100),
        ),
    ]
